name: Create Pull Request
on:
  push:
    branches:
      - develop
jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Open PR
        id: open_pr
        uses: rematocorp/open-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          from-branch: develop
          to-branch: test
          repository-owner: achin16
          repository: spring-data-neo4j