name: Create Pull Request
on:
  push:
    branches:
      - develop
jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Open PR
        id: open_pr
        uses: ajaychinthapalli/open-pull-request-action@3ba8b3d428a07c8157cc0e7e3b3d5e579febeacb
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          from-branch: develop
          to-branch: test
          repository-owner: ajaychinthapalli
          repository: spring-data-neo4j